apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: robot-shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: robot-shop
  template:
    metadata:
      labels:
        app: robot-shop
    spec:
      containers:
      - name: user-container
        image: nginx:latest
        ports:
        - containerPort: 80
